export type FormattingName =
    'bold'
    | 'italic'
    | 'underline'
    | 'code'
    | 'list-numbered'
    | 'list-dots'
    | 'paragraph-left'
    | 'paragraph-center'
    | 'paragraph-right'
    | 'table'
    | 'hidden'
    | 'link'
    | 'image'
    | 'text-color'
    | 'text-background-color'
    | 'insertorderedlist' // TODO: eliminar de aquí para abajo después de implementar el nuevo toolbar
    | 'insertunorderedlist'
    | 'justifyleft'
    | 'justifycenter'
    | 'justifyright'
    | 'hidetext';