import { ContainerProps } from './types/container-props.type.ts';

export const toolsConfig: ContainerProps[] = [
    {
        name: 'bold',
        icon: 'icon-set-bold',
        tag: 'strong',
        isBlock: false,
    },
    {
        name: 'italic',
        icon: 'icon-set-italic',
        tag: 'i',
        isBlock: false,
    },
    {
        name: 'underline',
        icon: 'icon-set-underline',
        tag: 'u',
        isBlock: false,
    },
    {
        name: 'code',
        icon: 'icon-set-code',
        tag: 'div',
        isBlock: true,
        classes: ['code-text'],
    },
    {
        name: 'list-numbered',
        icon: 'icon-set-list-numbered',
        tag: 'ol',
        isBlock: true,
    },
    {
        name: 'list-dots',
        icon: 'icon-set-list-dots',
        tag: 'ul',
        isBlock: true,
    },
    {
        name: 'paragraph-left',
        icon: 'icon-set-paragraph-left',
        tag: 'div',
        isBlock: true,
        styles: { textAlign: 'left' },
        groups: ['alignments'],
    },
    {
        name: 'paragraph-center',
        icon: 'icon-set-paragraph-center',
        tag: 'div',
        isBlock: true,
        styles: { textAlign: 'center' },
        groups: ['alignments'],
    },
    {
        name: 'paragraph-right',
        icon: 'icon-set-paragraph-right',
        tag: 'div',
        isBlock: true,
        styles: { textAlign: 'right' },
        groups: ['alignments'],
    },
    {
        name: 'hidden',
        icon: 'icon-set-hidden',
        tag: 'div',
        isBlock: false,
        classes: ['hidden-text'],
    },
    {
        name: 'table',
        icon: 'icon-insert-table',
        tag: 'table',
        isBlock: true,
    },
    {
        name: 'link',
        icon: 'icon-insert-link',
        tag: 'a',
        isBlock: false,
        attributes: { href: '' },
    },
    {
        name: 'image',
        icon: 'icon-insert-image',
        tag: 'img',
        isBlock: true,
        attributes: { src: '' },
    },
    {
        name: 'text-color',
        icon: 'icon-set-text-color',
        tag: 'span',
        isBlock: false,
        styles: { color: '' },
    },
    {
        name: 'text-background-color',
        icon: 'icon-set-text-background-color',
        tag: 'span',
        isBlock: false,
        styles: { backgroundColor: '' },
    },
];